#ifndef DETECTION_ENGINE_H
#define DETECTION_ENGINE_H

#include "Metrics.h"
#include "json.hpp"
#include <string>
#include <map>

using json = nlohmann::json;

struct ModelParams {
    double mean;
    double std_dev;
};

class DetectionEngine {
public:
    // Loads the model_params.json generated by export_params.py
    bool loadConfiguration(const std::string &configPath);

    // Core: Validates a metric against loaded Z-score thresholds
    // Returns true if an anomaly is detected
    bool validateMetric(const TelemetryMetric &tm, double zThreshold = 3.0);

private:
    std::map<std::string, ModelParams> thresholds;
};

#endif